"""empty message

Revision ID: 6d40ef6c2f3e
Revises: da82ed2e771b
Create Date: 2024-05-07 00:13:20.277791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d40ef6c2f3e'
down_revision = 'da82ed2e771b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
