"""empty message

Revision ID: b2f2a3ba617b
Revises: a1c09bd3fee8
Create Date: 2024-05-06 11:04:24.233006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f2a3ba617b'
down_revision = 'a1c09bd3fee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rewardType', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('followers', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('percentage', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdBy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updatedBy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rewards_pkey')
    )
    # ### end Alembic commands ###
