"""empty message

Revision ID: da82ed2e771b
Revises: 8b31203c3baa
Create Date: 2024-05-06 23:41:43.635605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da82ed2e771b'
down_revision = '8b31203c3baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('file_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_type')
        batch_op.drop_column('document_category')

    # ### end Alembic commands ###
